### ISSUE TITLE
Styling not working if you follow the documentation

### ISSUE THREAD

**Issue by RoelRoel** [Yopadd/vue-chartist#34]
I added 
Vue.use(require('vue-chartist')) 

to main.js and I followed the example. But now the chart looks ugly:

![image](https://user-images.githubusercontent.com/531248/42379613-8812e818-812b-11e8-9a75-4a355072105d.png)

Do I have to add the stylesheets manually and why is this not documented? 

**Update**: The documentations says: "This package include Chartist's javascript but not the stylesheet"

WTH? Why? How to include the stylesheets if you use webpack? (default Vue CLI tools)
I cannot add something to the Head in VueJS... So this means this lib is totally useless? Why did you bother to make it?

**Comment by hitautodestruct** [comment]
Hey @RoelRoel 
I got confused by this as well.
You can load the sass file from chartist in your vue component:
```
<style lang="scss">
@import '~chartist/dist/scss/chartist.scss';
</style>
```
**Note:** This is assuming you have sass-loader and vue-loader is configured for parsing sass.

Otherwise you can link to a cdn:
`<link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">`

> WTH? Why? How to include the stylesheets if you use webpack? (default Vue CLI tools)
I cannot add something to the Head in VueJS... So this means this lib is totally useless? Why did you bother to make it?

I am not the author of this plugin but it has saved me a lot of time wrapping chartist in a vue component and making sure everything is reactive.
Try using chartist without this plugin in vue :-)

**Comment by user4i** [comment]
@Yopadd Thanks for `vue-chartist`! :)

Please add this info to document

> You can load the sass file from chartist in your vue component:
> ```
> <style lang="scss">
> @import '~chartist/dist/scss/chartist.scss';
> </style>
> ```

We waste hours while find info by this issue about styling :(
